# Generated by Django 3.0 on 2020-01-07 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('student_class', models.CharField(choices=[('JSS 1A', 'JSS 1A'), ('JSS 1B', 'JSS 1B'), ('JSS 1C', 'JSS 1C'), ('JSS 2A', 'JSS 2A'), ('JSS 2B', 'JSS 2B'), ('JSS 2C', 'JSS 2C'), ('JSS 3A', 'JSS 3A'), ('JSS 3B', 'JSS 3B'), ('JSS 3C', 'JSS 3C'), ('SS 1A', 'SS 1A'), ('SS 1B', 'SS 1B'), ('SS 1C', 'SS 1C'), ('SS 2A', 'SS 2A'), ('SS 2B', 'SS 2B'), ('SS 2C', 'SS 2C'), ('SS 3A', 'SS 3A'), ('SS 3B', 'SS 3B'), ('SS 3C', 'SS 3C')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('term', models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM ')], max_length=15)),
                ('payment_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Fee',
                'verbose_name_plural': 'School Fees',
                'ordering': ('-student_class', '-surname'),
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(choices=[('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SS 1', 'SS 1'), ('SS 2', 'SS 2'), ('SS 3', 'SS 3')], max_length=15)),
                ('class_name', models.CharField(choices=[('JSS 1A', 'JSS 1A'), ('JSS 1B', 'JSS 1B'), ('JSS 1C', 'JSS 1C'), ('JSS 2A', 'JSS 2A'), ('JSS 2B', 'JSS 2B'), ('JSS 2C', 'JSS 2C'), ('JSS 3A', 'JSS 3A'), ('JSS 3B', 'JSS 3B'), ('JSS 3C', 'JSS 3C'), ('SS 1A', 'SS 1A'), ('SS 1B', 'SS 1B'), ('SS 1C', 'SS 1C'), ('SS 2A', 'SS 2A'), ('SS 2B', 'SS 2B'), ('SS 2C', 'SS 2C'), ('SS 3A', 'SS 3A'), ('SS 3B', 'SS 3B'), ('SS 3C', 'SS 3C')], max_length=15)),
            ],
            options={
                'ordering': ('class_name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=50, max_length=50, null=True)),
                ('house', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_year', models.CharField(max_length=10)),
                ('class_name', models.CharField(choices=[('JSS 1A', 'JSS 1A'), ('JSS 1B', 'JSS 1B'), ('JSS 1C', 'JSS 1C'), ('JSS 2A', 'JSS 2A'), ('JSS 2B', 'JSS 2B'), ('JSS 2C', 'JSS 2C'), ('JSS 3A', 'JSS 3A'), ('JSS 3B', 'JSS 3B'), ('JSS 3C', 'JSS 3C'), ('SS 1A', 'SS 1A'), ('SS 1B', 'SS 1B'), ('SS 1C', 'SS 1C'), ('SS 2A', 'SS 2A'), ('SS 2B', 'SS 2B'), ('SS 2C', 'SS 2C'), ('SS 3A', 'SS 3A'), ('SS 3B', 'SS 3B'), ('SS 3C', 'SS 3C')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('student_id', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='img/student')),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(choices=[('AA', 'AA'), ('A+', 'A+'), ('A-', 'A-'), ('0+', '0+')], max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ('-surname', 'first_name'),
            },
        ),
    ]
