# Generated by Django 3.0 on 2020-01-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolfee',
            name='fees',
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
