# Generated by Django 3.0 on 2020-01-02 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200102_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfee',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
