# Generated by Django 3.0 on 2020-01-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
