# Generated by Django 3.0 on 2020-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_class_master',
            field=models.BooleanField(default=False),
        ),
    ]
