# Generated by Django 3.0 on 2020-01-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userrole_is_class_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='is_class_master',
            new_name='is_master',
        ),
    ]
